### ISSUE TITLE
Time to train the model on PSM dataset

### ISSUE THREAD

**Issue by prithuls** [17000cyh/IMDiffusion#1]
Hello, could you provide an approximate duration it took you for training your architecture on PSM dataset? Also, the GPU configuration if you have that. I am trying to train this on PSM dataset and it's taking a lot of time than I expected.

Thanks.

**Comment by 17000cyh** [comment]
hi, when I use 3090 to train model for PSM, in each epoch, it takes me about 10 minutes for training and about 8 minutes for validation.  It usually takes about 12 epochs to achieves its optimal performance.

You took more time for training , which might be due to the fact that each script actually conducted 6 independent experiments. Considering that the Diffusion Model typically involves some randomness during training and inference, in order to investigate the stability of its performance, we conducted multiple experiments  within the 'exe_machine.py' script.

for training_epoch in range(0,6):

You can change it to

for training_epoch in range(0,1):


Actually, PSM is not the dataset which requires the most training resources. SWaT needs about two hour for each epoch while training and SMD has 28 subsets.

**Comment by prithuls** [comment]
Thank you for your comment!
